### ISSUE TITLE
After the number 8 slide the previous slides not repeating

### ISSUE THREAD

**Issue by LantosIstvan** [jonchretien/continuous-carousel#8]
In the demo example when it reaching number 8 the second time, there's no repeating. Is it a normal behavior? This is the same in latest Firefox and Chrome.

**Comment by LantosIstvan** [comment]
More precisely, the sequence reappears suddenly, when the first set of numbers completed, meaning slide 11 reaching the left side of the screen. But because of that, the right half of the screen is empty from slides.

**Comment by jonchretien** [comment]
Thanks for pointing this out, that's definitely a bug. I'll take a look.

**Comment by jonchretien** [comment]
Should hopefully be resolved with the latest version.
